name: Afterdark
author: proferabg
version: 1.2
api-version: 1.18
main: com.proferabg.afterdark.Afterdark
description: Mine as much as you can!
commands:
  afterdark:
    description: AfterDark command